config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get '/home', to: "pages#home"
  
  # get '/recipes', to: 'recipes/#index'
  # get '/recipes/new', to: 'recipes/#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes/#create'
  # get '/recipes/:id/edit', to: 'recipes/#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes/#update'
  # get '/recipes/:id', to: 'recipes/#show', as: 'recipe'
  # delete '/recipes/:id', to: 'recipes/#distroy'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new]
  
  get '/register', to: "chefs#new"
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#distroy"
  
  
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  has_many :likes
  before_save {self.email = email.downcase}
  validates :chefname,presence: true, length: {minimum: 3, maximum: 40}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false},format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe
  
  validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes
  validates :chef_id, presence: true
  validates :name, presence: true, length: {minimum: 5, maximum: 100}
  validates :summary, presence: true , length: {minimum: 20, maximum: 150}
  validates :description, presence: true, length: {minimum: 50, maximum: 500}
  
  mount_uploader :picture, PictureUploader
  #validate :picture_size
  default_scope -> {order(updated_at: :desc)} 
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
  private
    def picture_size
      if picture_size > 5.megabytes
        errors.add(:picture, "should be less than 5 MB")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user,:logged_in?
  
  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end
  
  def logged_in?
    !!current_user
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:edit,:update,:show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @chef = Chef.new
  end
  
  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      flash[:success] = "Congratulations! Your account has been created successfuly."
      session[:chef_id] = @chef.id
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
    #@chef = Chef.find(params[:id])
  end
  
  def update
    #@chef = Chef.find(params[:id])
    if @chef.update(chef_params)
      flash[:success] = "Your Profile has been updated successfuly."
      redirect_to recipes_path
    else
      render :edit
    end
  end
  
  def show
    #@chef = Chef.find(params[:id])
    @recipes = @chef.recipes.paginate(page: params[:page], per_page: 4)
  end
  
  private
    def chef_params
      params.require(:chef).permit(:chefname,:email,:password)
    end
    
    def require_same_user
      if current_user != @chef
        flash[:danger] = "You can only edit your profile."
        redirect_to root_path
      end
    end
    
    def set_chef
      @chef = Chef.find(params[:id])
    end

  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new
  end
  
  def create
    chef = Chef.find_by(email: params[:email])
    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:success] = "You are logged in."
      redirect_to recipes_path
    else
      flash[:danger] = "Invalid login."
      redirect_to login_path
    end
  end
  
  def distroy
    session[:chef_id] = nil
    flash[:success] = "You have logged out."
    redirect_to root_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_action :set_recipe, only: [:edit,:update,:show,:like]
  before_action :require_user, except: [:show,:index]
  before_action :require_same_user, only: [:edit, :update,:like]
  
  def index
    #@recipes = Recipe.all.sort_by{|likes| likes.thumbs_up_total}.reverse
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end
  
  def show
    #@recipe = Recipe.find(params[:id])
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user
    
    if @recipe.save
      flash[:success] = "Recipe was created successfuly."
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
    #@recipe = Recipe.find(params[:id])
  end
  
  def update
    #@recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updates successfuly."
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
    
  end
  
  def like
   #@recipe = Recipe.find(params[:id])
   like = Like.create(like: params[:like],chef: Chef.first,recipe: @recipe)
   if like.valid?
     flash[:success] = "Your secection was successful."
   else
     flash[:danger] = "Your can only like/dislike a recipe only once."
   end
   redirect_to :back
  end
  
  private
    def recipe_params
      params.require(:recipe).permit(:name,:summary,:description,:picture)
    end
    
    def require_same_user
      if current_user != @recipe.chef
        flash[:danger] = "This site is free and open to everyone, but our registered users can create, edit and  like recipe."
        redirect_to root_path
      end
    end
    
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
    
    def require_user
      if !logged_in?
        flash[:danger] = "This site is free and open to everyone, but our registered users can create, edit and  like recipe."
        redirect_to root_path
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: chef.chefname,class: 'gravatar')
  end
  
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2"> 
    <%= form_for(@chef) do |f| %>
      
      <%= f.label :Name %>
      <%= f.text_field :chefname %>
      
      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit(@chef.new_record? ? 'Register': 'Edit Profile', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/chefs/edit.html.erb
<p>
  <h1 class="center">Edit your profile.</h1>
  <hr/>
</p>

<%= render "chefs/form" %>

app/views/chefs/index.html.erb
<h1 class='center'>All Chefs.</h1>
<ul class="nav nav-tabs">
  <li>
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li class="active">
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>
<div class='row'>
  <div class='col-md-4 col-lg-offset-4 center'>
   <%= will_paginate @recipes %>
  </div>
</div

<% @chefs.each do |chef| %>
<div class='row'>
    <div class='col-md-4 col-lg-offset-4 center'>
      <section class='chef_info center'>
        <%= link_to gravatar_for(chef, size: 100),chef_path(chef) %>
        <h5>Chef Name: <%= link_to chef.chefname, chef_path(chef) %></h5>
      </section>
    </div>
</div>
<% end %>

app/views/chefs/new.html.erb
<p>
  <h1 class="center">Create an Account.</h1>
  <hr/>
</p>

<%= render "chefs/form" %>

app/views/chefs/show.html.erb
<p>
  <h1 class='center'><%= "Chef: " +@chef.chefname %></h1>
</p>
<hr/>

<div class='row'>
  <div class='col-md-4 col-lg-offset-4 center'>
    <section class='chef_info center'>
        <%= gravatar_for @chef, size: 100 %>
    </section>
    <br>
    <hr/>
  </div>
</div>  
  
<div class='row'>
  <div class='col-md-4 col-lg-offset-4 center'>
   <h4><em>Recipes:</em></h4>
   <%= will_paginate @recipes %>
  </div>
</div

<div class='row'>  
  <% @recipes.each do |recipe| %>
  <div class="col-lg-6 well col-lg-offset-3">
    <h4> <%= link_to recipe.name,recipe_path(recipe) %> </h4>
    <p> <%= recipe.summary %></p>
    <div class='pull-right'>
      <%= link_to like_recipe_path(recipe, like: true),method: :post do%>
      <i class='glyphicon glyphicon-thumbs-up'></i> &nbsp <%= recipe.thumbs_up_total %>
      <% end %>&nbsp&nbsp&nbsp&nbsp
      <%= link_to like_recipe_path(recipe, like: false),method: :post do%>
      <i class='glyphicon glyphicon-thumbs-down'></i> &nbsp <%= recipe.thumbs_down_total %>
      <% end %>
    </div>
    <span class='quiet'> <small>Created <%= time_ago_in_words(recipe.created_at) %> ago.</small> </span>
    &nbsp&nbsp
    <span class='quiet'> <small>Updated <%= time_ago_in_words(recipe.updated_at) %> ago.</small> </span>
  </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class='footer'>
  <p>&copy;myRecipes 2016. Contact: Pushkar Mishra.</p>
</div>

app/views/layouts/_messages.html.erb
<div class='row'>
  <div class='col-md-12'>
  <% flash.each do | message_type, message | %>
    <div class="alert alert-<%= message_type %>"><%= message %>
      <a class="close" data-dismis="alert">&#215;</a>
    </div>
  <% end %>  
  </div>
</div>

app/views/layouts/_nav.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to'myRecipes', root_path, class:"btn btn-lg btn-success", id: "logo" %> 
  
    <div class='nav_item'>
      <%= link_to 'link1',"",class:"btn btn-default btn-warning" %>
    </div>
    
    <div class='nav_item'>
      <%= link_to 'link2',"",class:"btn btn-default btn-warning" %>
    </div>
    <% if logged_in? %>
    <div class='nav_item'>
      <%= link_to 'New Recipe',new_recipe_path,class:"btn btn-default btn-warning" %>
    </div>
    <ul class='nav_item pull-right'>
    <li class = 'dropdown'>
      <%= link_to '#', class: "btn btn-default btn-warning dropdown-toggle", 'data-toggle' => 'dropdown' do %>
      <span>Hi <%= current_user.chefname %> <b class='caret'></b>
      <% end %>
      <ul class='dropdown-menu'>
        <li><%= link_to 'View Profile', chef_path(current_user) %></li>
        <li><%= link_to 'Edit Profile', edit_chef_path(current_user) %></li>
        <li class='divider'> </li>
        <li><%= link_to 'Logout', logout_path %></li>
      </ul>
    </li>
    </ul>
    <% else %>
    <div class='nav_item pull-right'>
      <%= link_to 'Login',login_path,class:"btn btn-success" %>
    </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myRecipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render"layouts/nav" %>

<div class="container">
  <%= render"layouts/messages" %>
  <%= yield %>
  <%= render"layouts/footer" %>

</div>

</body>
</html>

app/views/logins/new.html.erb
<h1 class='center'>Log In</h1>

<div class="row">
  <div class="well col-md-6 col-md-offset-3">
  <%= form_tag '/login' do%>
  
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    
    <%= submit_tag "Login", class: "btn btn-success" %>
    
  <%end%>
  </div>
</div>

app/views/pages/home.html.erb
<div class='center jumbotron'>
  <h1>Welcome to myRecipeManager!</h1>
  <h3> myRecipe Manager is ONE place to store and organize the recipes you find – in a format that can be carried & used directly in the kitchen.</h3>
  <%= link_to'Sign up now!', register_path, class:"btn btn-lg btn-success"%> 
</div>

<div class='row'>
  <div class='col-lg-4'>
    <h3 class='midrow'>Browser recipe as Guest user!</h3>
     <p>Browse recipes as a guest user and sign up latter.</h4>
     <p><%= link_to 'Browse Recipes',recipes_path,class:"btn btn-warning btn-samll" %></p>
  </div>
  <div class='col-lg-4'>
    <h3 class='midrow'>Sign In to your account!</h3>
     <p>Add/Update your recipes, like/dislike and many more.</h4>
     <p><%= link_to 'Login to your account',login_path,class:"btn btn-warning btn-samll" %></p>
  </div>
  <div class='col-lg-4'>
    <h3 class='midrow'>Browser recipe as Guest user!</h3>
     <p>Browse recipes as a guest user and sign up latter.</h4>
     <p><%= link_to 'Browse Recipes',recipes_path,class:"btn btn-warning btn-samll" %></p>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2"> 
    <%= form_for(@recipe, html: {multipart: true}) do |f| %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>
      <span class='picture'>
        <%= f.file_field :picture, accept: 'image/gif,image/png,image/jpec,image/jpg' %>
      </span>
      <%= f.submit(@recipe.new_record? ? 'Create Recipe': 'Edit Recipe', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type='javascript'>
  $('#recipe_picture').bind('change', function(){
    size_in_megabytes = file[0].size/1024/1024;
    if (size_in_megabytes > 5){
      alert("Maximum file size allowed is 5MB")
    }
    
  });
</script>

app/views/recipes/edit.html.erb
<p>
  <h1 class="center">Edit recipe.</h1>
  <hr/>
</p>

<%= render "recipes/form" %>

app/views/recipes/index.html.erb
<h1 class='center'>All Recipes.</h1>
<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate %>
<% @recipes.each do |recipe| %>
  <div class='row'>
    <div class='col-md-2'>
      <section class='chef_info center'>
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
        <h5>Chef Name: <%= link_to recipe.chef.chefname, chef_path(recipe.chef) %></h5>
      </section>
    </div>
    
    <div class='col-lg-6 well'>
      <h4> <%= link_to recipe.name,recipe_path(recipe) %> </h4>
      <p> <%= recipe.summary %></p>
      <div class='pull-right'>
        <%= link_to like_recipe_path(recipe, like: true),method: :post do%>
        <i class='glyphicon glyphicon-thumbs-up'></i> &nbsp <%= recipe.thumbs_up_total %>
        <% end %>&nbsp&nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(recipe, like: false),method: :post do%>
        <i class='glyphicon glyphicon-thumbs-down'></i> &nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
      <span class='quiet'> <small>Created <%= time_ago_in_words(recipe.created_at) %> ago.</small> </span>
      &nbsp&nbsp
      <span class='quiet'> <small>Updated <%= time_ago_in_words(recipe.updated_at) %> ago.</small> </span>
    </div>
    <div class='col-md-4'>
      <%= image_tag(recipe.picture.url, size: "250x150",class: "gravatar") if recipe.picture? %>
    </div>
  </div>
</hr>
<% end %>


<%= will_paginate %>

app/views/recipes/new.html.erb
<p>
  <h1 class="center">Create a new recipe.</h1>
  <hr/>
</p>

<%= render "recipes/form" %>

app/views/recipes/show.html.erb
<p>
  <h1><%= @recipe.name %></h1>
</p>
</hr>
<div class='row'>
  <div class='col-md-4 pull-right center'>
    <section class='chef_info center'>
        <%= link_to gravatar_for(@recipe.chef, size: 100),chef_path(@recipe.chef) %>
        <h5>Brought to you by: <%= link_to @recipe.chef.chefname, chef_path(@recipe.chef) %></h5>
      </section>
  </div>
    
    <div class='col-md-8 center'>
      <% if logged_in? and @recipe.chef == current_user %>
      <%= link_to "Edit this Recipe",edit_recipe_path, class: "btn btn-success pull-right" %>
      <% end %>
      <h3><%= @recipe.summary %> </h3>
      <div class='show_recipe'>
        <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
      </div>
      <div class='well'>
        <%= simple_format(@recipe.description) %>
        <div class='pull-right'>
        <%= link_to like_recipe_path(@recipe, like: true),method: :post do%>
        <i class='glyphicon glyphicon-thumbs-up'></i> &nbsp <%= @recipe.thumbs_up_total %>
        <% end %>&nbsp&nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(@recipe, like: false),method: :post do%>
        <i class='glyphicon glyphicon-thumbs-down'></i> &nbsp <%= @recipe.thumbs_down_total %>
        <% end %>
        </div>
      </div>
    </div>
</div>

<%= link_to "Return to recipe listing",recipes_path,class: "btn btn-warning" %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div class='alert alert-danger col-md-8 col-md-offset-2'>
      <h4>Please correct the following errors:</h4>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>